### PR TITLE
bump eco-goinfra to v0.0.0-20240806143944-e49acf61eb1b

### PR DESCRIPTION
**Pull request by kononovn**

### CODE REVIEW

**Review by klaskosk — APPROVED** [review]
cnf/ran changes lgtm

**Review by trewest — APPROVED** [review]
/lgtm

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Review by cdvultur — APPROVED** [review]
/lgtm

**Review by sebrandon1 — APPROVED** [review]

**Pull request merged**
