### PR TITLE
system-test: simplify call to WaitForRegex

### PR DESCRIPTION
**Pull request by edcdavid**

### CODE REVIEW

**Comment by klaskosk** [comment]
@edcdavid There's a Github action that will automatically bump the eco-goinfra dependency every night now. Let me know if you need it before tomorrow and we can merge this then

**Comment by edcdavid** [comment]
> @edcdavid There's a Github action that will automatically bump the eco-goinfra dependency every night now. Let me know if you need it before tomorrow and we can merge this then

@klaskosk tomorrow would be fine but is it going to work automatically? This PR modifies an existing interface so it will need manual input I believe

**Comment by edcdavid** [comment]
> > @edcdavid There's a Github action that will automatically bump the eco-goinfra dependency every night now. Let me know if you need it before tomorrow and we can merge this then
> 
> @klaskosk tomorrow would be fine but is it going to work automatically? This PR modifies an existing interface so it will need manual input I believe

Nevermind, it should merge automatically without issues. I'll rename and rebase this PR once the latest infra merges

**Review by klaskosk — APPROVED** [review]
/lgtm

**Review by mcornea — APPROVED** [review]

**Pull request merged**
