### PR TITLE
cnf-network:MetalLB: speaker pods replaced by frr-8ks pods

### PR DESCRIPTION
**Pull request by evgenLevin**

### CODE REVIEW

**Comment by gkopels** [comment]
Hi Evgeny, you test the code? If so this looks like an easy fix to migrate the cnf gotests to 4.17.

**Comment by evgenLevin** [comment]
> Hi Evgeny, you test the code? If so this looks like an easy fix to migrate the cnf gotests to 4.17.

Yes, it was tested and looks good. I'm working on cnf gotests PR as well, it's should be ready soon

**Comment by gkopels** [comment]
lgtm

**Review by ajaggapa — APPROVED** [review]
LGTM 👍

**Comment by gkopels** [comment]
lgtm

**Review by gkopels — APPROVED** [review]

**Pull request merged**
